"""db_boocking

Revision ID: 0a00496d1bfb
Revises: 3a4c5c2eebfd
Create Date: 2025-11-08 15:35:52.610251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a00496d1bfb'
down_revision = '3a4c5c2eebfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
