"""Add trener table columns3

Revision ID: 5adc543f39a8
Revises: 6e85e3768007
Create Date: 2025-10-26 20:37:58.339737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adc543f39a8'
down_revision = '6e85e3768007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vk', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('vk')
        batch_op.drop_column('telegram')
        batch_op.drop_column('instagram')

    # ### end Alembic commands ###
