"""Add avatar + text in db.trener

Revision ID: 6e85e3768007
Revises: eaa8612d9dde
Create Date: 2025-10-26 00:27:16.793891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e85e3768007'
down_revision = 'eaa8612d9dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('text')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
