"""booking fix

Revision ID: 80d5e9d94b4a
Revises: cd015fa185eb
Create Date: 2025-11-02 21:36:28.313942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d5e9d94b4a'
down_revision = 'cd015fa185eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trener_name', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'trener', ['trener_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trener_name')

    # ### end Alembic commands ###
