"""Add trener relationship and schedules

Revision ID: 84d7f4c4cb25
Revises: 5adc543f39a8
Create Date: 2025-10-28 11:27:38.861335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d7f4c4cb25'
down_revision = '5adc543f39a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trener_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'trener', ['trener_id'], ['id'])
        batch_op.drop_column('trener_name')

    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.drop_column('specialization')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trener_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trener_id')

    # ### end Alembic commands ###
