"""Add trener relationship and schedules

Revision ID: cd015fa185eb
Revises: 84d7f4c4cb25
Create Date: 2025-10-28 13:39:04.796728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd015fa185eb'
down_revision = '84d7f4c4cb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.drop_column('specialization')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
