"""Add trener all_name2

Revision ID: eaa8612d9dde
Revises: bd1c76e57a29
Create Date: 2025-10-25 14:13:54.494479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa8612d9dde'
down_revision = 'bd1c76e57a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_name', sa.String(length=60), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.drop_column('all_name')

    # ### end Alembic commands ###
